sudo: required

services:
  - docker

before_install:
  - docker build -t swapnilj01/react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true swapnilj01/react-app npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-ap-south-1-302304551949"
  bucker_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY